# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hitcher' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hitcher

pod 'Firebase/Core'
pod 'Firebase/Database'

  target 'hitcherTests' do
    # Pods for testing
  end

  target 'hitcherUITests' do
    # Pods for testing
  end
  
end
